import sys

TIMEOUT = 0.1
'''Colores para prints'''
COLOR_GREEN = '\033[92m'
COLOR_BLUE = '\033[94m'
COLOR_RED = '\033[91m'
COLOR_YELLOW = '\033[93m'
COLOR_PURPLE = '\033[95m'
COLOR_BOLD = '\033[1m'
COLOR_END = '\033[0m'

'''Endianess'''
BYTEORDER = byteorder = sys.byteorder

'''Protocolo'''
CHUNKSIZE = 4096
MAX_FILE_SIZE = 4000000000  # 4GB
SELECTIVE_REPEAT = 0x1
STOP_AND_WAIT = 0x2

UPLOAD_REQUEST_OPCODE = 0x0
FILE_TRANSFER_RESPONSE_OPCODE = 0x1
DOWNLOAD_REQUEST_OPCODE = 0x2
INIT_DOWNLOAD_ACK_OPCODE = 0X3
PACKET_OPCODE = 0x4
ACK_OPCODE = 0x5
STOP_FILE_TRANSFER_OPCODE = 0x6
FINAL_ACK_OPCODE = 0x7
DOWNLOAD_REQUEST_RESPONSE_OPCODE = 0xB

'''Paquetes'''
REQUEST_CONTENT = "20s"
OPCODE_MASK = 0xF

OPCODE_FORMAT = 'c'
CHECKSUM_FORMAT = '4s'
NSEQ_FORMAT = '4s'
HEADER_FORMAT = OPCODE_FORMAT + CHECKSUM_FORMAT + NSEQ_FORMAT

PROTOCOL_FORMAT = 'c'
FILE_NAME_FORMAT = '20s'
FILE_SIZE_FORMAT = '16s'
MD5 = '16s'
UPLOAD_REQUEST_FORMAT = PROTOCOL_FORMAT + \
    FILE_NAME_FORMAT + FILE_SIZE_FORMAT + MD5
DOWNLOAD_REQUEST_FORMAT = PROTOCOL_FORMAT + FILE_NAME_FORMAT
DOWNLOAD_RESPONSE_FORMAT = MD5 + FILE_SIZE_FORMAT

FILE_TRANSFER_TYPE_FORMAT = '4s'

PACKAGE_FORMAT = '4096s'

STOP_FILE_TRANSFER_FORMAT = '16s1s'

'''Largo de paquetes (en bytes)'''
FILE_TRANSFER_REQUEST_SIZE = 62
FILE_TRANSFER_TYPE_RESPONSE_SIZE = 13
ACK_SIZE = 9
PACKET_SIZE = 4105
DOWNLOAD_RESPONSE_SIZE = 41

'''Errores'''
FILE_DOES_NOT_EXIST_OPCODE = 0xC
NO_DISK_SPACE_OPCODE = 0xD
FILE_TOO_BIG_OPCODE = 0xE


FILE_TRANSFER_RESPONSE_FORMAT = 'I'

ERROR_CODE = -1
STOP_FILE_TRANSFER_SIZE = 26
DOWNLOAD_RESPONSE_SIZE = 41

'''Timeouts'''
SELECTIVE_REPEAT_PACKET_TIMEOUT = TIMEOUT*2
SELECTIVE_REPEAT_PKT_TOUT = TIMEOUT*5
CLIENT_SOCKET_TIMEOUTS = 50
LAST_ACK_PACKET_TIMEOUT = 50

'''Log Levels'''
LOG_LEVEL_ERROR = 0
LOG_LEVEL_WARNING = 1
LOG_LEVEL_INFO = 2
LOG_LEVEL_DEBUG = 3

'''State'''
STATE_ERROR = 0x0
STATE_OK = 0x1

'''Tipos de protocolo'''
STOP_AND_WAIT = 0
SELECTIVE_REPEAT = 1
